name: weather-app
version: 0.0.1
summary: Your ReactNative Ubuntu Application
description: This is a description of WeatherApp
confinement: devmode
apps:
  WeatherApp:
    command: bin/WeatherApp --local=./share/js/index.js --plugins-path=./plugins

parts:
  nodejs:
    plugin: nodejs

  react-native-app:
    plugin: copy
    source: ..
    files:
      bin/WeatherApp: bin/WeatherApp
      bin/ubuntu-server.js: bin/ubuntu-server.js
      share: share
      plugins: plugins

